name: Node CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Prepare environment
        run: |
          corepack enable
          yarn

      - name: Disable AppArmor
        # https://github.com/puppeteer/puppeteer/pull/13196
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - name: Test in Chromium
        run: |
          yarn ci
        env:
          CI: true
          HEADLESS: true
