name: Publish prerelease

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Test in Chromium
        run: |
          yarn
          yarn ci
        env:
          CI: true
          HEADLESS: true

  prerelease:
    name: Prerelease
    runs-on: ubuntu-latest
    timeout-minutes: 15

    needs:
      - test

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Check release is desired
        id: do-publish
        run: |
          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
            echo "No Token"
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Publish nightly"
            echo "publish=nightly" >> $GITHUB_OUTPUT
          else
            echo "Publish experimental"
            echo "publish=experimental" >> $GITHUB_OUTPUT
          fi
      - name: Prepare Environment
        if: ${{ steps.do-publish.outputs.publish }}
        run: |
          yarn install
          yarn build
        env:
          CI: true
      - name: Bump version and build
        if: ${{ steps.do-publish.outputs.publish }}
        run: |
          COMMIT_TIMESTAMP=$(git log -1 --pretty=format:%ct HEAD)
          COMMIT_DATE=$(date -d @$COMMIT_TIMESTAMP +%Y%m%d-%H%M%S)
          GIT_HASH=$(git rev-parse --short HEAD)
          PRERELEASE_TAG=nightly-$(echo "${{ github.ref_name }}" | sed -r 's/[^a-z0-9]+/-/gi')
          yarn version --no-changelog --no-commit-hooks --no-git-tag-version --prepatch --preid "$PRERELEASE_TAG-$COMMIT_DATE-$GIT_HASH" --yes
        env:
          CI: true
      - name: Publish to NPM
        if: ${{ steps.do-publish.outputs.publish }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          echo "registry: https://registry.npmjs.org/" >> .yarnrc
          yarn publish --access public --tag ${{ steps.do-publish.outputs.publish }} --yes --verbose
        env:
          CI: true
